// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADinaKuWHQduxZRIV2CiO3-1tTTYE7fPg',
    appId: '1:524017728374:web:f375e05f214a51f4a0d857',
    messagingSenderId: '524017728374',
    projectId: 'cosialla-v3',
    authDomain: 'cosialla-v3.firebaseapp.com',
    storageBucket: 'cosialla-v3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzuFcXTrnsV3hZehQXddhbif1rSucGYgs',
    appId: '1:524017728374:android:9cf8afd664cd6613a0d857',
    messagingSenderId: '524017728374',
    projectId: 'cosialla-v3',
    storageBucket: 'cosialla-v3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZM79Ljs6Wcw8DR_oUWRSc9XjsCj_HR2w',
    appId: '1:524017728374:ios:5d9cc25057627867a0d857',
    messagingSenderId: '524017728374',
    projectId: 'cosialla-v3',
    storageBucket: 'cosialla-v3.appspot.com',
    iosClientId: '524017728374-ilgo3ng272v1osjqu10iqcqd0hh5ilgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cosialla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZM79Ljs6Wcw8DR_oUWRSc9XjsCj_HR2w',
    appId: '1:524017728374:ios:5d9cc25057627867a0d857',
    messagingSenderId: '524017728374',
    projectId: 'cosialla-v3',
    storageBucket: 'cosialla-v3.appspot.com',
    iosClientId: '524017728374-ilgo3ng272v1osjqu10iqcqd0hh5ilgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cosialla',
  );
}
